#!/usr/bin/env bash
# =============================================================================
# dev_setup.sh  –  One-command local dev environment for EV Charger Portal
#
# What this script does:
#   1. Verifies / installs dependencies (mosquitto, Python packages)
#   2. Creates a local Mosquitto config (anonymous, port 11883)
#   3. Starts Mosquitto in the background
#   4. Writes tests/dev_options.json pointing at the local broker
#   5. Starts uvicorn with --reload on port 8080
#   6. On exit (Ctrl-C), stops Mosquitto cleanly
#   7. Prints interactive test instructions
#
# Usage:
#   cd ev_portal/rootfs/app
#   ./dev_setup.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BROKER_HOST="127.0.0.1"
BROKER_PORT=11883          # avoid clashing with any real broker on 1883
UVICORN_PORT=8080
RUN_DIR="${TMPDIR:-/tmp}/ev_portal_dev"
MOSQUITTO_CONF="${RUN_DIR}/mosquitto.conf"
MOSQUITTO_PID="${RUN_DIR}/mosquitto.pid"
MOSQUITTO_LOG="${RUN_DIR}/mosquitto.log"
DEV_OPTIONS="${SCRIPT_DIR}/tests/dev_options.json"

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}▶  $*${RESET}"; }
success() { echo -e "${GREEN}✔  $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠  $*${RESET}"; }
die()     { echo -e "${RED}✖  $*${RESET}" >&2; exit 1; }
banner()  { echo -e "\n${BOLD}$*${RESET}"; }

# ── Cleanup on exit ───────────────────────────────────────────────────────────
MOSQUITTO_PID_VAL=""
cleanup() {
    echo ""
    info "Shutting down..."
    if [[ -n "$MOSQUITTO_PID_VAL" ]] && kill -0 "$MOSQUITTO_PID_VAL" 2>/dev/null; then
        kill "$MOSQUITTO_PID_VAL" 2>/dev/null && success "Mosquitto stopped"
    fi
}
trap cleanup EXIT INT TERM

# =============================================================================
# 1. DEPENDENCIES
# =============================================================================
banner "── Step 1 / 4 : Checking dependencies ────────────────────────────────"

# mosquitto binary
if ! command -v mosquitto &>/dev/null; then
    if command -v brew &>/dev/null; then
        info "mosquitto not found – installing via Homebrew..."
        brew install mosquitto
    else
        die "mosquitto not found and Homebrew is not available.\n   Install manually: https://mosquitto.org/download/"
    fi
fi
success "mosquitto found at $(command -v mosquitto)"

# mosquitto_sub (for the test instructions – same package, just logging)
if ! command -v mosquitto_sub &>/dev/null; then
    warn "mosquitto_sub not found – subscriber test commands won't work until you install the full mosquitto package."
fi

# Python packages
info "Installing / verifying Python dependencies..."
pip install -q -r "${SCRIPT_DIR}/requirements.txt"
success "Python packages ready"

# =============================================================================
# 2. MOSQUITTO CONFIG & START
# =============================================================================
banner "── Step 2 / 4 : Starting Mosquitto broker ────────────────────────────"

mkdir -p "$RUN_DIR"

cat > "$MOSQUITTO_CONF" <<EOF
# Auto-generated by dev_setup.sh – do not edit manually
listener ${BROKER_PORT} ${BROKER_HOST}
allow_anonymous true
log_dest file ${MOSQUITTO_LOG}
log_type error
log_type warning
EOF

# Kill any stale mosquitto left from a previous run on our dev port
if [[ -f "$MOSQUITTO_PID" ]]; then
    OLD_PID="$(cat "$MOSQUITTO_PID")"
    kill "$OLD_PID" 2>/dev/null || true
    rm -f "$MOSQUITTO_PID"
fi

mosquitto -c "$MOSQUITTO_CONF" -d -p "$BROKER_PORT"
# Grab the PID of the just-started broker
MOSQUITTO_PID_VAL=$(pgrep -n -f "mosquitto -c ${MOSQUITTO_CONF}" || true)
echo "$MOSQUITTO_PID_VAL" > "$MOSQUITTO_PID"

# Wait for the port to be ready
info "Waiting for broker on ${BROKER_HOST}:${BROKER_PORT}..."
for i in $(seq 1 50); do
    nc -z "$BROKER_HOST" "$BROKER_PORT" 2>/dev/null && break
    sleep 0.1
    [[ $i -eq 50 ]] && die "Broker did not start within 5 s – check ${MOSQUITTO_LOG}"
done
success "Mosquitto running on ${BROKER_HOST}:${BROKER_PORT}  (pid ${MOSQUITTO_PID_VAL})"

# =============================================================================
# 3. WRITE DEV OPTIONS
# =============================================================================
banner "── Step 3 / 4 : Writing dev_options.json ─────────────────────────────"

cat > "$DEV_OPTIONS" <<EOF
{
  "mqtt_host": "${BROKER_HOST}",
  "mqtt_port": ${BROKER_PORT},
  "mqtt_username": "",
  "mqtt_password": ""
}
EOF
success "$(basename "$DEV_OPTIONS") updated → host=${BROKER_HOST} port=${BROKER_PORT}"

export EV_OPTIONS_PATH="$DEV_OPTIONS"

# =============================================================================
# 4. INTERACTIVE TEST INSTRUCTIONS
# =============================================================================
banner "── Step 4 / 4 : Ready – interactive test commands ────────────────────"

cat <<INSTRUCTIONS

  ${BOLD}Server${RESET}   http://localhost:${UVICORN_PORT}
  ${BOLD}Broker${RESET}   ${BROKER_HOST}:${BROKER_PORT}  (anonymous, dev only)
  ${BOLD}Logs${RESET}     ${MOSQUITTO_LOG}

  Open a ${BOLD}second terminal${RESET} and subscribe to all EV topics:

    ${CYAN}mosquitto_sub -h ${BROKER_HOST} -p ${BROKER_PORT} -t 'ev/#' -v${RESET}

  Then trigger a charger session (third terminal or browser):

    ${CYAN}curl "http://localhost:${UVICORN_PORT}/health"${RESET}
    ${CYAN}curl "http://localhost:${UVICORN_PORT}/start?charger_id=charger-01"${RESET}
    ${CYAN}curl "http://localhost:${UVICORN_PORT}/start?charger_id=charger-02"${RESET}

  Expected subscriber output:
    ev/charger-01/start {"charger_id": "charger-01", "timestamp": "..."}

  Validation tests (no broker needed):
    ${CYAN}pytest -v tests/test_main.py${RESET}

  Integration tests (reuses this broker):
    ${CYAN}pytest -v tests/test_integration.py${RESET}

  Press ${BOLD}Ctrl-C${RESET} to stop uvicorn and Mosquitto.

──────────────────────────────────────────────────────────────────────────────
INSTRUCTIONS

# =============================================================================
# START UVICORN (foreground – Ctrl-C stops everything via the trap)
# =============================================================================
cd "$SCRIPT_DIR"
exec uvicorn main:app \
    --host 0.0.0.0 \
    --port "$UVICORN_PORT" \
    --reload \
    --log-level info
